### ISSUE TITLE
Evaluation Error

### ISSUE THREAD

**Issue by yellowjs0304** [david8862/keras-YOLOv3-model-set#113]
Hi, Thank u for sharing nice work.
I tried your work with my own dataset. But some error occurred when using  eval.py 

`
Traceback (most recent call last):
  File "eval.py", line 1337, in <module>
    main()
  File "eval.py", line 1328, in main
    model, model_format = load_eval_model(args.model_path)
  File "eval.py", line 1262, in load_eval_model
    model = load_model(model_path, compile=False, custom_objects=custom_object_dict)
  File "C:\ProgramData\Anaconda3\envs\keraspython\lib\site-packages\tensorflow\python\keras\saving\save.py", line 182, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "C:\ProgramData\Anaconda3\envs\keraspython\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 178, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "C:\ProgramData\Anaconda3\envs\keraspython\lib\site-packages\tensorflow\python\keras\saving\model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\ProgramData\Anaconda3\envs\keraspython\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 175, in deserialize
    printable_module_name='layer')
  File "C:\ProgramData\Anaconda3\envs\keraspython\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 358, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\ProgramData\Anaconda3\envs\keraspython\lib\site-packages\tensorflow\python\keras\engine\functional.py", line 617, in from_config
    config, custom_objects)
  File "C:\ProgramData\Anaconda3\envs\keraspython\lib\site-packages\tensorflow\python\keras\engine\functional.py", line 1214, in reconstruct_from_config
    process_node(layer, node_data)
  File "C:\ProgramData\Anaconda3\envs\keraspython\lib\site-packages\tensorflow\python\keras\engine\functional.py", line 1162, in process_node
    output_tensors = layer(input_tensors, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keraspython\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 926, in __call__
    input_list)
  File "C:\ProgramData\Anaconda3\envs\keraspython\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1117, in _functional_construction_call
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keraspython\lib\site-packages\tensorflow\python\keras\layers\core.py", line 903, in call
    result = self.function(inputs, **kwargs)
  File "C:/Users/JSHwang/Desktop/2020-2TA/ML_Chapter_2/keras-YOLOv3-model-set-master/yolo3/loss.py", line 287, in yolo3_loss
    object_mask = y_true[l][..., 4:5]
TypeError: 'range_iterator' object is not subscriptable
`
Could u please share any tip please?

**Comment by david8862** [comment]
@yellowjs0304 seems you're running eval.py with a training checkpoint. Pls make sure to follow [Model dump](https://github.com/david8862/keras-YOLOv3-model-set#model-dump) to dump out inference model from training checkpoint, and then do the evaluation.

**Comment by yellowjs0304** [comment]
Thank u I didn't see that part!
It works well~
