### ISSUE TITLE
ValueError: Unknown layer: AddMetric

### ISSUE THREAD

**Issue by rootadminWalker** [david8862/keras-YOLOv3-model-set#118]
Hi, I'm training YOLOv3_darknet with the VOC2012 dataset, the model successfully trained but when I evaluate it, it throws me the following error:
```
Traceback (most recent call last):
  File "eval.py", line 1337, in <module>
    main()
  File "eval.py", line 1328, in main
    model, model_format = load_eval_model(args.model_path)
  File "eval.py", line 1262, in load_eval_model
    model = load_model(model_path, compile=False, custom_objects=custom_object_dict)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 212, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/serialization.py", line 89, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/generic_utils.py", line 192, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py", line 1121, in from_config
    process_layer(layer_data)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py", line 1105, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/serialization.py", line 89, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/generic_utils.py", line 181, in deserialize_keras_object
    config, module_objects, custom_objects, printable_module_name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/generic_utils.py", line 166, in class_and_config_for_serialized_keras_object
    raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown layer: AddMetric
```
My environment is
```
Ubuntu 18.04.5
GPU Nvidia Geforce GTX 1060
Python 3.6.9
Tensorflow 1.14.0
Keras 2.2.4-tf
Numpy 1.17.3
```
Can somebody help me? Thanks a lot

**Comment by david8862** [comment]
@rootadminWalker seems you're running eval.py with a training checkpoint. Pls make sure to follow [Model dump](https://github.com/david8862/keras-YOLOv3-model-set#model-dump) to dump out inference model from training checkpoint, and then do the evaluation.

**Comment by rootadminWalker** [comment]
@david8862 Thanks, now the problem is solved. But how does the inference model works?

**Comment by rootadminWalker** [comment]
@david8862 Thanks, now the problem is solved. I'll now close the issue
