### ISSUE TITLE
Some problems in the training process.

### ISSUE THREAD

**Issue by Pangzaijun** [david8862/keras-YOLOv3-model-set#136]
Pascal VOC AP evaluation
PO: AP 0.0000, precision 0.0000, recall 0.0000
LOP: AP 0.0000, precision 0.0000, recall 0.0000
CR: AP 0.0000, precision 0.0000, recall 0.0000
SI: AP 0.0000, precision 0.0000, recall 0.0000
ND: AP 0.0000, precision 0.0000, recall 0.0000
mAP@IoU=0.50 result: 0.000000
mPrec@IoU=0.50 result: 0.000000
mRec@IoU=0.50 result: 0.000000
7/7 [==============================] - 30s 4s/step - loss: 55.9396 - location_loss: 2.0135 - confidence_loss: 50.0306 - class_loss: 3.7570 - val_loss: 1030.2776 - val_location_loss: 1.2786 - val_confidence_loss: 1024.8455 - val_class_loss: 4.0152
Unfreeze and continue training, to fine-tune.
Train on 112 samples, val on 12 samples, with batch size 16, input_shape (416, 416).
Epoch 21/250
Traceback (most recent call last):
  File "train.py", line 291, in <module>
    main(args)
  File "train.py", line 212, in main
    callbacks=callbacks)
  File "/home/pzj/anaconda3/envs/yolo/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 1296, in fit_generator
    steps_name='steps_per_epoch')
  File "/home/pzj/anaconda3/envs/yolo/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_generator.py", line 265, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "/home/pzj/anaconda3/envs/yolo/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 1017, in train_on_batch
    outputs = self.train_function(ins)  # pylint: disable=not-callable
  File "/home/pzj/anaconda3/envs/yolo/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3476, in __call__
    run_metadata=self.run_metadata)
  File "/home/pzj/anaconda3/envs/yolo/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[16,512,26,26] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node training_2/Adam/gradients/gradients/AddN_200-1-TransposeNHWCToNCHW-LayoutOptimizer}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[loss_1/add/_5519]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[16,512,26,26] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node training_2/Adam/gradients/gradients/AddN_200-1-TransposeNHWCToNCHW-LayoutOptimizer}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.

**Comment by david8862** [comment]
@Pangzaijun this should be GPU OOM after transfer traning stage, which is possible since more GPU memory is needed after unfreezing the backbone. You may need to check your GPU memory usage.

**Comment by MrSouwbauck** [comment]
Put a smaller batch_size. You will reduce memory usage
