### ISSUE TITLE
Different model 

### ISSUE THREAD

**Issue by ViniciusAbrao** [david8862/keras-YOLOv3-model-set#145]
I am not sure if the commands for the YOLOv3 would be like that:

wget -O weights/yolov3.weights https://pjreddie.com/media/files/yolov3.weights

python tools/model_converter/convert.py cfg/yolov3.cfg weights/yolov3.weights weights/yolov3.h5

python yolo.py --image --model_type yolo3_ --weights_path weights/yolov3.h5 --anchors_path configs/yolo3_anchors.txt

Please could you correct in case of some mistake. With that commands I am getting the message:

    raise ValueError('This model type is not supported now')
ValueError: This model type is not supported now

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yolo.py", line 437, in <module>
    main()
  File "yolo.py", line 409, in main
    yolo = YOLO_np(**vars(args))
  File "yolo.py", line 69, in __init__
    self.yolo_model = self._generate_model()
  File "yolo.py", line 104, in _generate_model
    assert yolo_model.layers[-1].output_shape[-1] == \
UnboundLocalError: local variable 'yolo_model' referenced before assignment

**Comment by MrSouwbauck** [comment]
model_type is not right. You need to choose one of the backbone listed in yolo3/model.py -> yolo3_model_map.
The default one is --model_type=yolo3_mobilenet_lite

Backbones weights are automatically download one first completion (except for darknet i think).

**Comment by ViniciusAbrao** [comment]
In the case of using:

python tools/model_converter/convert.py cfg/yolov3.cfg weights/yolov3.weights weights/yolov3.h5

python yolo.py --image --model_type yolo3_ --weights_path weights/yolov3.h5 --anchors_path configs/yolo3_anchors.txt

Which model must be choose to match with the number of layers?

**Comment by david8862** [comment]
@ViniciusAbrao you can use "yolo3_darknet" for official YOLOv3 model

**Comment by Ayumu-J-S** [comment]
@ViniciusAbrao 
Yes, try downloading the weights from the darknet53 model. You can just do
`wget https://pjreddie.com/media/files/darknet53.conv.74`
and convert the weight to h5 form in order to use it in keras.

As long as you keep the the converted weights in weights directory, you do not have to specify where the weights file is located.
