### ISSUE TITLE
"variable shape are incompatible" error

### ISSUE THREAD

**Issue by tingjhenjiang** [david8862/keras-YOLOv3-model-set#176]
Hello,
I've trained a darknet yolov3 model to detect my own objects.
I set the yolo3-tiny model to have an input size at w640h640 to detect only 1 class object, and trained by [the darknet project](https://github.com/AlexeyAB/darknet).
I get the final weights file called "yolov3-tiny_best.weights", and try to convert it to keras format model.
This command works well:
python tools/model_converter/convert.py cfg/myown-model-yolov3-tiny.cfg weights/myown-model-yolov3-tiny_best.weights weights/yolov3-tiny.h5

But when I try to run this command:
python yolo.py --model_type=tiny_yolo3_darknet --weights_path=weights/yolov3-tiny.h5 --anchors_path=configs/myown-model-yolo3-tiny_anchors.txt --classes_path=configs/myown-model-yolov3-tiny_classes.txt --model_image_size=640x640 --image

(myown-model-yolo3-tiny_anchors.txt is copied from tiny_yolo3_anchors.txt)
(the content of myown-model-yolov3-tiny_classes.txt has only one line of text)

There is an error message:
`ValueError('Cannot assign to variable predict_conv_1/kernel:0 due to variable shape (1, 1, 512, 255) and value shape (18, 512, 1, 1) are incompatible')
Traceback (most recent call last):
  File "yolo.py", line 91, in _generate_model
    yolo_model, _ = get_yolo3_model(self.model_type, num_feature_layers, num_anchors, num_classes, input_shape=self.model_image_size + (3,), model_pruning=self.pruning_model)
  File "F:\coffeebeans\keras-YOLOv3-model-set\yolo3\model.py", line 213, in get_yolo3_model
    model_body = model_function(input_tensor, num_anchors//2, num_classes, weights_path=weights_path)
  File "F:\coffeebeans\keras-YOLOv3-model-set\yolo3\models\yolo3_darknet.py", line 224, in custom_tiny_yolo3_body
    base_model.load_weights(weights_path, by_name=False)
  File "D:\ProgramData\Miniconda3\envs\kerasYOLOv3\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2326, in load_weights
    hdf5_format.load_weights_from_hdf5_group(f, self.layers)
  File "D:\ProgramData\Miniconda3\envs\kerasYOLOv3\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 713, in load_weights_from_hdf5_group
    backend.batch_set_value(weight_value_tuples)
  File "D:\ProgramData\Miniconda3\envs\kerasYOLOv3\lib\site-packages\tensorflow\python\util\dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "D:\ProgramData\Miniconda3\envs\kerasYOLOv3\lib\site-packages\tensorflow\python\keras\backend.py", line 3804, in batch_set_value
    x.assign(np.asarray(value, dtype=dtype_numpy(x)))
  File "D:\ProgramData\Miniconda3\envs\kerasYOLOv3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 901, in assign
    (tensor_name, self._shape, value_tensor.shape))
ValueError: Cannot assign to variable predict_conv_1/kernel:0 due to variable shape (1, 1, 512, 255) and value shape (18, 512, 1, 1) are incompatible`

**Comment by david8862** [comment]
@tingjhenjiang  for `tiny_yolo3_darknet` model, current implementation will try to load COCO pretrained weights `weights/yolov3-tiny.h5` [here](https://github.com/david8862/keras-YOLOv3-model-set/blob/master/yolo3/model.py#L160) first when building the model structure, and then your own weights file. So if you want to try yolo.py, you need to follow the quick start guide to generate COCO pretrained `weights/yolov3-tiny.h5` and avoid converting your own model at same place.
Or you can also choose [validate_yolo.py](https://github.com/david8862/keras-YOLOv3-model-set/blob/master/tools/evaluation/validate_yolo.py) to inference directly with the converted model.

**Comment by tingjhenjiang** [comment]
@david8862 Got it! Problems solved by referencing to the codes in eval.py! Thanks!
