### ISSUE TITLE
canot train YOLOv3 with gpu  

### ISSUE THREAD

**Issue by s07362022** [david8862/keras-YOLOv3-model-set#214]
I use : 
cuda 11.2 
cudnn 8

and pp install the requirement.txt from document,
I just replace tensorflow-gpu to tensorflow-gpu==2.5.0

then, I cannot run the code..... 

`Traceback (most recent call last):
  File "train.py", line 20, in <module>
    from common.callbacks import EvalCallBack, CheckpointCleanCallBack, DatasetShuffleCallBack
  File "E:\workspace\DL\keras_YOLOv3_model_set-master\common\callbacks.py", line 15, in <module>
    from eval import eval_AP
  File "E:\workspace\DL\keras_YOLOv3_model_set-master\eval.py", line 19, in <module>
    import MNN
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\MNN\__init__.py", line 7, in <module>
    from _mnncengine import *
Exception: initMNN: init numpy failed`

I try to install other tensorflow-gpu, but all fail.
I want to know how to fix it.

or

what version is True by RTX3070

**Comment by david8862** [comment]
seems to be a MNN env issue. what's your MNN & numpy version?
