### ISSUE TITLE
Inference for yolov4-tiny-darknet is giving error

### ISSUE THREAD

**Issue by Abhishek672** [david8862/keras-YOLOv3-model-set#220]
Hey @david8862,
Thanks for such amazing work.

I am having problem doing inference on yolov4tiny using yolo.py. I have converted .weights to .h5 and generated a anchors.txt file.
while running the snippet : 

 !python yolo.py --model_type=tiny_yolo4_darknet \
--weights_path=weights/keras_darknet.h5 \
--anchors_path=weights/keras_darknet_anchors.txt \
--classes_path=configs/classes.txt \
--image \
--input=img_0001.jpg \
--output=result.jpg

I am getting error : 
ValueError('This model type is not supported now')
Traceback (most recent call last):
  File "yolo.py", line 91, in _generate_model
    yolo_model, _ = get_yolo3_model(self.model_type, num_feature_layers, num_anchors, num_classes, input_shape=self.model_input_shape + (3,), model_pruning=self.pruning_model)
  File "/content/keras-YOLOv3-model-set/yolo3/model.py", line 228, in get_yolo3_model
    raise ValueError('This model type is not supported now')
ValueError: This model type is not supported now

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yolo.py", line 437, in <module>
    main()
  File "yolo.py", line 409, in main
    yolo = YOLO_np(**vars(args))
  File "yolo.py", line 69, in __init__
    self.yolo_model = self._generate_model()
  File "yolo.py", line 104, in _generate_model
    assert yolo_model.layers[-1].output_shape[-1] == \
UnboundLocalError: local variable 'yolo_model' referenced before assignment.

Is this repository compatible with AlexyAB yolov4-tiny darknet?

Thanks

**Comment by david8862** [comment]
@Abhishek672 sorry I didn't involve `tiny_yolo4_darknet` model type in official process support. Maybe you can try [validate_yolo.py](https://github.com/david8862/keras-YOLOv3-model-set/blob/master/tools/evaluation/validate_yolo.py) for inference if you have been able to convert the darknet .cfg and .weights to Keras .h5

**Comment by Abhishek672** [comment]
@david8862 Thanks for the reply it works!!

For doing inference I want to set certain values of --iou and --confidence_score. In the validate_yolo.py there is no such option. I also tried to look inside the code but it is also not there. What are the default values of iou and confidence_score we are using while doing inference?

Thanks

**Comment by Abhishek672** [comment]
Hey @david8862 
I want to convert the .h5 model of yolov4-tiny to .pb and then .tflite. I used *keras_to_tensorflow.py* to convert .h5 to frozen .pb model followed by conversion to tflite. Everything runs well up to this point. But if I try to do detection in tflite then it gives me an error ValueError: operands could not be broadcast together with shapes (1,26,18,1) (1,26,21,18).

does the keras_to_tensorflow.py works with yolov4-tiny also?

Thanks

**Comment by Abhishek672** [comment]
So @david8862,
If I choose yolov4-tiny with cspdarknet53 tiny as the backbone, It is not possible to do the training. Do you know any other repositories where this is implemented?

Thanks
