### ISSUE TITLE
convert yolo4 to .h5 error

### ISSUE THREAD

**Issue by BehsanAndishAMK** [david8862/keras-YOLOv3-model-set#227]
I want to convert custom YoloV4 model to h5 but I've got error,
[cfg file](https://drive.google.com/file/d/1-0EEH1ewxkLMCUZyCc-0gbR9nIr1KGmi/view?usp=sharing)
[weight file](https://drive.google.com/file/d/1_WWCr9-oT1p0zibLmG8AmNTTtUC3RIHB/view?usp=sharing)

error:

```
Loading weights.
Weights Header:  0 2 5 [256000]
Parsing Darknet config.
Creating Keras model.
Parsing section net_0
Parsing section convolutional_0
conv2d bn mish (3, 3, 3, 32)
2022-04-18 09:20:58.775758: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
Parsing section convolutional_1
conv2d bn mish (3, 3, 32, 64)
Parsing section convolutional_2
conv2d bn mish (1, 1, 64, 64)
Parsing section route_0
Parsing section convolutional_3
conv2d bn mish (1, 1, 64, 64)
Parsing section convolutional_4
conv2d bn mish (1, 1, 64, 32)
Parsing section convolutional_5
conv2d bn mish (3, 3, 32, 64)
Parsing section shortcut_0
Parsing section convolutional_6
conv2d bn mish (1, 1, 64, 64)
Parsing section route_1
Concatenating route layers: [<KerasTensor: shape=(None, 208, 208, 64) dtype=float32 (created by layer 'activation_6')>, <KerasTensor: shape=(None, 208, 208, 64) dtype=float32 (created by layer 'activation_2')>]
Parsing section convolutional_7
conv2d bn mish (1, 1, 128, 64)
Parsing section convolutional_8
conv2d bn mish (3, 3, 64, 128)
Parsing section convolutional_9
conv2d bn mish (1, 1, 128, 64)
Parsing section route_2
Parsing section convolutional_10
conv2d bn mish (1, 1, 128, 64)
Parsing section convolutional_11
conv2d bn mish (1, 1, 64, 64)
Parsing section convolutional_12
conv2d bn mish (3, 3, 64, 64)
Parsing section shortcut_1
Parsing section convolutional_13
conv2d bn mish (1, 1, 64, 64)
Parsing section convolutional_14
conv2d bn mish (3, 3, 64, 64)
Parsing section shortcut_2
Parsing section convolutional_15
conv2d bn mish (1, 1, 64, 64)
Parsing section route_3
Concatenating route layers: [<KerasTensor: shape=(None, 104, 104, 64) dtype=float32 (created by layer 'activation_15')>, <KerasTensor: shape=(None, 104, 104, 64) dtype=float32 (created by layer 'activation_9')>]
Parsing section convolutional_16
conv2d bn mish (1, 1, 128, 128)
Parsing section convolutional_17
conv2d bn mish (3, 3, 128, 256)
Parsing section convolutional_18
conv2d bn mish (1, 1, 256, 128)
Parsing section route_4
Parsing section convolutional_19
conv2d bn mish (1, 1, 256, 128)
Parsing section convolutional_20
conv2d bn mish (1, 1, 128, 128)
Parsing section convolutional_21
conv2d bn mish (3, 3, 128, 128)
Parsing section shortcut_3
Parsing section convolutional_22
conv2d bn mish (1, 1, 128, 128)
Parsing section convolutional_23
conv2d bn mish (3, 3, 128, 128)
Parsing section shortcut_4
Parsing section convolutional_24
conv2d bn mish (1, 1, 128, 128)
Parsing section convolutional_25
conv2d bn mish (3, 3, 128, 128)
Parsing section shortcut_5
Parsing section convolutional_26
conv2d bn mish (1, 1, 128, 128)
Parsing section convolutional_27
conv2d bn mish (3, 3, 128, 128)
Parsing section shortcut_6
Parsing section convolutional_28
conv2d bn mish (1, 1, 128, 128)
Parsing section convolutional_29
conv2d bn mish (3, 3, 128, 128)
Parsing section shortcut_7
Parsing section convolutional_30
conv2d bn mish (1, 1, 128, 128)
Parsing section convolutional_31
conv2d bn mish (3, 3, 128, 128)
Parsing section shortcut_8
Parsing section convolutional_32
conv2d bn mish (1, 1, 128, 128)
Parsing section convolutional_33
conv2d bn mish (3, 3, 128, 128)
Parsing section shortcut_9
Parsing section convolutional_34
conv2d bn mish (1, 1, 128, 128)
Parsing section convolutional_35
conv2d bn mish (3, 3, 128, 128)
Parsing section shortcut_10
Parsing section convolutional_36
conv2d bn mish (1, 1, 128, 128)
Parsing section route_5
Concatenating route layers: [<KerasTensor: shape=(None, 52, 52, 128) dtype=float32 (created by layer 'activation_36')>, <KerasTensor: shape=(None, 52, 52, 128) dtype=float32 (created by layer 'activation_18')>]
Parsing section convolutional_37
conv2d bn mish (1, 1, 256, 256)
Parsing section convolutional_38
conv2d bn mish (3, 3, 256, 512)
Parsing section convolutional_39
conv2d bn mish (1, 1, 512, 256)
Parsing section route_6
Parsing section convolutional_40
conv2d bn mish (1, 1, 512, 256)
Parsing section convolutional_41
conv2d bn mish (1, 1, 256, 256)
Parsing section convolutional_42
conv2d bn mish (3, 3, 256, 256)
Parsing section shortcut_11
Parsing section convolutional_43
conv2d bn mish (1, 1, 256, 256)
Parsing section convolutional_44
conv2d bn mish (3, 3, 256, 256)
Parsing section shortcut_12
Parsing section convolutional_45
conv2d bn mish (1, 1, 256, 256)
Parsing section convolutional_46
conv2d bn mish (3, 3, 256, 256)
Parsing section shortcut_13
Parsing section convolutional_47
conv2d bn mish (1, 1, 256, 256)
Parsing section convolutional_48
conv2d bn mish (3, 3, 256, 256)
Parsing section shortcut_14
Parsing section convolutional_49
conv2d bn mish (1, 1, 256, 256)
Parsing section convolutional_50
conv2d bn mish (3, 3, 256, 256)
Parsing section shortcut_15
Parsing section convolutional_51
conv2d bn mish (1, 1, 256, 256)
Parsing section convolutional_52
conv2d bn mish (3, 3, 256, 256)
Parsing section shortcut_16
Parsing section convolutional_53
conv2d bn mish (1, 1, 256, 256)
Parsing section convolutional_54
conv2d bn mish (3, 3, 256, 256)
Parsing section shortcut_17
Parsing section convolutional_55
conv2d bn mish (1, 1, 256, 256)
Parsing section convolutional_56
conv2d bn mish (3, 3, 256, 256)
Parsing section shortcut_18
Parsing section convolutional_57
conv2d bn mish (1, 1, 256, 256)
Parsing section route_7
Concatenating route layers: [<KerasTensor: shape=(None, 26, 26, 256) dtype=float32 (created by layer 'activation_57')>, <KerasTensor: shape=(None, 26, 26, 256) dtype=float32 (created by layer 'activation_39')>]
Parsing section convolutional_58
conv2d bn mish (1, 1, 512, 512)
Parsing section convolutional_59
conv2d bn mish (3, 3, 512, 1024)
Parsing section convolutional_60
conv2d bn mish (1, 1, 1024, 512)
Parsing section route_8
Parsing section convolutional_61
conv2d bn mish (1, 1, 1024, 512)
Parsing section convolutional_62
conv2d bn mish (1, 1, 512, 512)
Parsing section convolutional_63
conv2d bn mish (3, 3, 512, 512)
Parsing section shortcut_19
Parsing section convolutional_64
conv2d bn mish (1, 1, 512, 512)
Parsing section convolutional_65
conv2d bn mish (3, 3, 512, 512)
Traceback (most recent call last):
  File "tools/model_converter/convert.py", line 433, in <module>
    main(parser.parse_args())
  File "tools/model_converter/convert.py", line 193, in main
    buffer=weights_file.read(weights_size * 4))
TypeError: buffer is too small for requested array
```

**Comment by david8862** [comment]
@BehsanAndishAMK how did you generate the .weights file? I compare your cfg with standard yolov4, there's only 1 following difference in model params except class number. But your .weights is much smaller than standard yolov4.weights (73M vs 246M)
<img width="624" alt="企业微信截图_16503793241112" src="https://user-images.githubusercontent.com/25219223/164031006-e981066f-3edc-4b57-aaf6-38b3570e6c64.png">

**Comment by maybehieu** [comment]
any update on this problem yet? I also have this error, I'll leave my config file and weights below. Weights's about ~240mb, net architecture is a little bit different (Yolov3). Thank you.
[config](https://drive.google.com/file/d/1bzS7YhM-V0Gh-njHeyc4l42eKye4Xi4U/view?usp=sharing)
[weights](https://drive.google.com/file/d/1Ny0PQLqe_aNx219DrRVAKUnmZuG5lqN1/view?usp=sharing)

error log:
command `!python3 tools/model_converter/convert.py cfg/a.cfg weight.weights weights/weight.h5`

log:
```
Loading weights.
Weights Header:  0 2 5 [740768]
Parsing Darknet config.
Creating Keras model.
Parsing section net_0
Parsing section convolutional_0
conv2d bn leaky (3, 3, 3, 32)
2022-04-21 09:21:29.628195: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
Parsing section convolutional_1
conv2d bn leaky (3, 3, 32, 64)
Parsing section convolutional_2
conv2d bn leaky (1, 1, 64, 32)
Parsing section convolutional_3
conv2d bn leaky (3, 3, 32, 64)
Parsing section shortcut_0
Parsing section convolutional_4
conv2d bn leaky (3, 3, 64, 128)
Parsing section convolutional_5
conv2d bn leaky (1, 1, 128, 64)
Parsing section convolutional_6
conv2d bn leaky (3, 3, 64, 128)
Parsing section shortcut_1
Parsing section convolutional_7
conv2d bn leaky (1, 1, 128, 64)
Parsing section convolutional_8
conv2d bn leaky (3, 3, 64, 128)
Parsing section shortcut_2
Parsing section convolutional_9
conv2d bn leaky (3, 3, 128, 256)
Parsing section convolutional_10
conv2d bn leaky (1, 1, 256, 128)
Parsing section convolutional_11
conv2d bn leaky (3, 3, 128, 256)
Parsing section shortcut_3
Parsing section convolutional_12
conv2d bn leaky (1, 1, 256, 128)
Parsing section convolutional_13
conv2d bn leaky (3, 3, 128, 256)
Parsing section shortcut_4
Parsing section convolutional_14
conv2d bn leaky (1, 1, 256, 128)
Parsing section convolutional_15
conv2d bn leaky (3, 3, 128, 256)
Parsing section shortcut_5
Parsing section convolutional_16
conv2d bn leaky (1, 1, 256, 128)
Parsing section convolutional_17
conv2d bn leaky (3, 3, 128, 256)
Parsing section shortcut_6
Parsing section convolutional_18
conv2d bn leaky (1, 1, 256, 128)
Parsing section convolutional_19
conv2d bn leaky (3, 3, 128, 256)
Parsing section shortcut_7
Parsing section convolutional_20
conv2d bn leaky (1, 1, 256, 128)
Parsing section convolutional_21
conv2d bn leaky (3, 3, 128, 256)
Parsing section shortcut_8
Parsing section convolutional_22
conv2d bn leaky (1, 1, 256, 128)
Parsing section convolutional_23
conv2d bn leaky (3, 3, 128, 256)
Parsing section shortcut_9
Parsing section convolutional_24
conv2d bn leaky (1, 1, 256, 128)
Parsing section convolutional_25
conv2d bn leaky (3, 3, 128, 256)
Parsing section shortcut_10
Parsing section convolutional_26
conv2d bn leaky (3, 3, 256, 512)
Parsing section convolutional_27
conv2d bn leaky (1, 1, 512, 256)
Parsing section convolutional_28
conv2d bn leaky (3, 3, 256, 512)
Parsing section shortcut_11
Parsing section convolutional_29
conv2d bn leaky (1, 1, 512, 256)
Parsing section convolutional_30
conv2d bn leaky (3, 3, 256, 512)
Parsing section shortcut_12
Parsing section convolutional_31
conv2d bn leaky (1, 1, 512, 256)
Parsing section convolutional_32
conv2d bn leaky (3, 3, 256, 512)
Traceback (most recent call last):
  File "tools/model_converter/convert.py", line 433, in <module>
    main(parser.parse_args())
  File "tools/model_converter/convert.py", line 193, in main
    buffer=weights_file.read(weights_size * 4))
TypeError: buffer is too small for requested array
```

**Comment by david8862** [comment]
@maybehieu seems your cfg and weights file are unavailable now...

**Comment by maybehieu** [comment]
@david8862 my apologies, it should be available now, can you check it again? Thank you.

**Comment by maybehieu** [comment]
I see, will check it out later, thanks!
