### ISSUE TITLE
AttributeError: module 'tensorflow.python.keras.api._v1.keras.layers' has no attribute 'Conv1DTranspose'

### ISSUE THREAD

**Issue by kz258852** [david8862/keras-YOLOv3-model-set#236]
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    from tensorflow_model_optimization.sparsity import keras as sparsity
  File "/home/kz/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_model_optimization/__init__.py", line 86, in <module>
    from tensorflow_model_optimization.python.core.api import clustering
  File "/home/kz/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_model_optimization/python/core/api/__init__.py", line 16, in <module>
    from tensorflow_model_optimization.python.core.api import clustering
  File "/home/kz/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_model_optimization/python/core/api/clustering/__init__.py", line 16, in <module>
    from tensorflow_model_optimization.python.core.api.clustering import keras
  File "/home/kz/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_model_optimization/python/core/api/clustering/keras/__init__.py", line 19, in <module>
    from tensorflow_model_optimization.python.core.clustering.keras.cluster import cluster_scope
  File "/home/kz/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_model_optimization/python/core/clustering/keras/cluster.py", line 22, in <module>
    from tensorflow_model_optimization.python.core.clustering.keras import cluster_wrapper
  File "/home/kz/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_model_optimization/python/core/clustering/keras/cluster_wrapper.py", line 24, in <module>
    from tensorflow_model_optimization.python.core.clustering.keras import clustering_registry
  File "/home/kz/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py", line 57, in <module>
    class ClusteringRegistry(object):
  File "/home/kz/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py", line 65, in ClusteringRegistry
    layers.Conv1DTranspose: ['kernel'],
  File "/home/kz/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/util/module_wrapper.py", line 193, in __getattr__
    attr = getattr(self._tfmw_wrapped_module, name)
AttributeError: module 'tensorflow.python.keras.api._v1.keras.layers' has no attribute 'Conv1DTranspose'

**Comment by kz258852** [comment]
Bro, the tensorflow-gpu versions I used are 1.15.0 and 2.0.0. This problem occurred when I was running the train.py. Is this caused by the tensorflow-gpu version? Which version of tensorflow-gpu is more appropriate? Thank u
