### ISSUE TITLE
ValueError: Unrecognized keyword arguments passed to Conv2D:

### ISSUE THREAD

**Issue by namejinnameyuan** [david8862/keras-YOLOv3-model-set#250]
The following error occurs when using convert.py

 python /home/dragino/yolo/Yolo-Fastest/keras-YOLOv3-model-set/tools/model_converter/fastest_1.1_160/convert.py --config_path /home/dragino/yolo/Yolo-Fastest/COCO_Dataset/yolo-fastest-1.1_160_person.cfg --weights_path /home/dragino/yolo/Yolo-Fastest/COCO_Dataset/model/yolo-fastest-1_100000.weights --output_path /home/dragino/yolo/Yolo-Fastest/COCO_Dataset/model/yolo-fastest-1.1_160_person.h5
2024-09-03 06:28:25.181894: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-09-03 06:28:25.190015: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-03 06:28:25.199257: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-03 06:28:25.201942: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-03 06:28:25.209395: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-03 06:28:25.599303: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Loading weights.
Weights Header:  0 2 5 [3200000]
Parsing Darknet config.
Creating Keras model.
Parsing section net_0
Parsing section convolutional_0
/home/dragino/yolo/Yolo-Fastest/keras-YOLOv3-model-set/tools/model_converter/fastest_1.1_160/convert.py:463: DeprecationWarning: `product` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `prod` instead.
  _main(config_path, weights_path, output_path)
conv2d bn relu6 (3, 3, 1, 8)
Traceback (most recent call last):
  File "/home/dragino/yolo/Yolo-Fastest/keras-YOLOv3-model-set/tools/model_converter/fastest_1.1_160/convert.py", line 463, in <module>
    _main(config_path, weights_path, output_path)
  File "/home/dragino/yolo/Yolo-Fastest/keras-YOLOv3-model-set/tools/model_converter/fastest_1.1_160/convert.py", line 226, in _main
    conv_layer = (Conv2D(
                  ^^^^^^^
  File "/home/dragino/yolo/lib/python3.12/site-packages/keras/src/layers/convolutional/conv2d.py", line 109, in __init__
    super().__init__(
  File "/home/dragino/yolo/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py", line 107, in __init__
    super().__init__(activity_regularizer=activity_regularizer, **kwargs)
  File "/home/dragino/yolo/lib/python3.12/site-packages/keras/src/layers/layer.py", line 285, in __init__
    raise ValueError(
ValueError: Unrecognized keyword arguments passed to Conv2D: {'weights': [array([[[[-0.06568899, -0.01998245,  0.23580368,  0.07110792,
           0.10956422,  0.1775481 , -0.1460538 ,  0.17278786]],

        [[ 0.0326125 ,  0.06673886,  0.9205416 ,  0.11603189,
           0.17709488, -0.13391306, -1.0329187 ,  0.21816015]],

        [[-0.02793978,  0.17466497,  0.3779089 , -0.02541469,
          -0.0273804 , -0.4333609 , -0.39139387,  0.08723172]]],

       [[[-0.51842767,  0.03935617,  0.21275678,  0.32264784,
           0.7678143 ,  0.30079642, -0.08603575,  0.27156684]],

        [[-1.1129417 ,  0.67044294,  1.1232518 ,  0.6125584 ,
           0.71447587, -0.3356362 , -0.77100766,  0.11470585]],

        [[-0.17094198,  0.5019581 ,  0.78665143,  0.0601312 ,
          -0.01930593, -1.1148578 , -0.2676109 ,  0.3221662 ]]],

       [[[-0.43147665, -0.33181298, -0.3015046 ,  0.29004085,
           0.9952198 ,  0.18380788,  0.17127149, -0.06260248]],

        [[-0.8178367 ,  0.24492387,  0.2960787 ,  0.62761885,
           0.8391471 , -0.12027573,  0.30649394,  0.03464032]],

        [[ 0.10950593,  0.42654032,  0.11321529, -0.06972235,
          -0.15183514, -0.99156165,  0.19460474,  0.25298938]]]],
      dtype=float32)]}

**Comment by namejinnameyuan** [comment]
Wrong
