### ISSUE TITLE
yolo3_head issue with converting model to TFLite or loading model

### ISSUE THREAD

**Issue by henry2304** [david8862/keras-YOLOv3-model-set#50]
Hi, I've been trying to convert a saved h5 file to tflite with the tools/post_train_quant_convert.py script, but I've been having issues with yolo3_head not being defined.  For context, I've been using model_type=tiny_yolo3_mobilenetv3small_lite with the train.py script, and running on tensorflow 2.1.0 and 1.15.0 both seem to run into the same issue.  To get around the issue, I've also tried importing yolo3_head and adding it to the custom_object_dict, but then I get a slightly different issue.  Does anyone know what the problem might be?  The exact command for the first error is below, and I'll post the second error in another post.  Thanks for any help!

[~/code/keras-YOLOv3-model-set]$ python tools/post_train_quant_convert.py --keras_model_file="logs/015/trained_final.h5" --annotation_file="../yolo3/all_gc_test_dlnm_ylabels.txt" --model_input_shape=416x416 --sample_num=30 --output_file=model_quant.tflite

/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow/python/keras/layers/core.py:1030: UserWarning: yolo3.loss is not loaded, but a Lambda layer uses it. It may cause errors.
  , UserWarning)
Traceback (most recent call last):
  File "tools/post_train_quant_convert.py", line 73, in <module>
    main()
  File "tools/post_train_quant_convert.py", line 68, in main
    post_train_quant_convert(args.keras_model_file, args.annotation_file, args.sample_num, model_input_shape, args.output_file)
  File "tools/post_train_quant_convert.py", line 29, in post_train_quant_convert
    model = load_model(keras_model_file, custom_objects=custom_object_dict)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 184, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 178, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 109, in deserialize
    printable_module_name='layer')
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 373, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 987, in from_config
    config, custom_objects)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 2029, in reconstruct_from_config
    process_node(layer, node_data)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1977, in process_node
    output_tensors = layer(input_tensors, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 922, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow/python/keras/layers/core.py", line 888, in call
    result = self.function(inputs, **kwargs)
  File "/home/ubuntu/code/keras-YOLOv3-model-set/yolo3/loss.py", line 284, in yolo3_loss
    grid, raw_pred, pred_xy, pred_wh = yolo3_head(yolo_outputs[l], anchors[anchor_mask[l]], num_classes, input_shape, calc_loss=True)
NameError: name 'yolo3_head' is not defined

**Comment by henry2304** [comment]
If I add the following lines to line 29 of the post_train_quant_convert.py file, it seems to resolve the first issue, but it still doesn't seem to work:
from yolo3.postprocess import yolo3_head
custom_object_dict['yolo3_head'] = yolo3_head

I still get a different error below and a warning about yolo3.loss not being loaded, and wondering if there's anything else I need to do to fix it?  If anyone has any suggestions about fixing it, please let me know.  Thanks!

/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow/python/keras/layers/core.py:1030: UserWarning: yolo3.loss is not loaded, but a Lambda layer uses it. It may cause errors.
  , UserWarning)
Traceback (most recent call last):
  File "tools/post_train_quant_convert.py", line 75, in <module>
    main()
  File "tools/post_train_quant_convert.py", line 70, in main
    post_train_quant_convert(args.keras_model_file, args.annotation_file, args.sample_num, model_input_shape, args.output_file)
  File "tools/post_train_quant_convert.py", line 31, in post_train_quant_convert
    model = load_model(keras_model_file, custom_objects=custom_object_dict)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 184, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 178, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 109, in deserialize
    printable_module_name='layer')
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 373, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 987, in from_config
    config, custom_objects)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 2029, in reconstruct_from_config
    process_node(layer, node_data)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1977, in process_node
    output_tensors = layer(input_tensors, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 922, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/tensorflow/python/keras/layers/core.py", line 888, in call
    result = self.function(inputs, **kwargs)
  File "/home/ubuntu/code/keras-YOLOv3-model-set/yolo3/loss.py", line 285, in yolo3_loss
    anchors[anchor_mask[l]], num_classes, input_shape, calc_loss=True)
TypeError: list indices must be integers or slices, not list

**Comment by david8862** [comment]
@henry2304 you need to follow [model-dump](https://github.com/david8862/keras-YOLOv3-model-set#model-dump) part to dump out inference model from training checkpoint first, and then do the tflite model convert

**Comment by henry2304** [comment]
Ahh, thanks for the quick reply!  I missed that was needed earlier, but it looks like it's working now.  This is a really useful repository with lots of models and tools btw - great work here, @david8862!
