### ISSUE TITLE
ValueError: No such layer: leaky_re_lu_8

### ISSUE THREAD

**Issue by amindehnavi** [david8862/keras-YOLOv3-model-set#52]
Hi
when I use 'tiny_yolo_v3' pretrained model in train.py, I got the following error.could you help me to solve that?
Error :
/content/keras-YOLOv3-model-set
WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
Load weights weights/yolov3-tiny.h5.
Load weights weights/yolov3-tiny.h5.
Traceback (most recent call last):
  File "train.py", line 282, in <module>
    main(args)
  File "train.py", line 139, in main
    model = get_train_model(args.model_type, anchors, num_classes, weights_path=args.weights_path, freeze_level=freeze_level, optimizer=optimizer, label_smoothing=args.label_smoothing, model_pruning=args.model_pruning, pruning_end_step=pruning_end_step)
  File "/content/keras-YOLOv3-model-set/yolo3/model.py", line 204, in get_yolo3_train_model
    model_body, backbone_len = get_yolo3_model(model_type, num_feature_layers, num_anchors, num_classes, model_pruning=model_pruning, pruning_end_step=pruning_end_step)
  File "/content/keras-YOLOv3-model-set/yolo3/model.py", line 158, in get_yolo3_model
    model_body = model_function(input_tensor, num_anchors//2, num_classes, weights_path=weights_path)
  File "/content/keras-YOLOv3-model-set/yolo3/models/yolo3_darknet.py", line 279, in custom_tiny_yolo3_body
    y1 = base_model.get_layer('leaky_re_lu_8').output
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py", line 563, in get_layer
    raise ValueError('No such layer: ' + name)
ValueError: No such layer: leaky_re_lu_8

**Comment by david8862** [comment]
@amindehnavi what's your TF version? I didn't meet such problem on TF 1.14/15 or 2.2, but I've commit a fix for that to make the model construction more stable. You can have a try on latest code.

**Comment by amindehnavi** [comment]
@david8862 My TF version is 2.2. Thank you for your fix, it worked.
i have another question :
when I train the tiny_yolov3_darknet on my own dataset I get the following result:
AP = 0.9828 , Precision = 0.1453 , recall = 0.9959
@ Iou = 0.5 :
mAP = 98.2826
mPrec = 14.5258
mRec = 99.588
Evaluation time cost = 8.11
--> my dataset has just one class
do you have an idea?why AP is high but Precision not?

**Comment by david8862** [comment]
Usually it's caused by the default "--conf_threshold=0.001" param when you use eval.py to do the evaluation. You can try to change to "--conf_threshold=0.1" to get more reasonable result.

> @david8862 My TF version is 2.2. Thank you for your fix, it worked.
> i have another question :
> when I train the tiny_yolov3_darknet on my own dataset I get the following result:
> AP = 0.9828 , Precision = 0.1453 , recall = 0.9959
> @ Iou = 0.5 :
> mAP = 98.2826
> mPrec = 14.5258
> mRec = 99.588
> Evaluation time cost = 8.11
> --> my dataset has just one class
> do you have an idea?why AP is high but Precision not?

**Comment by amindehnavi** [comment]
> Usually it's caused by the default "--conf_threshold=0.001" param when you use eval.py to do the evaluation. You can try to change to "--conf_threshold=0.1" to get more reasonable result.
> 
> > @david8862 My TF version is 2.2. Thank you for your fix, it worked.
> > i have another question :
> > when I train the tiny_yolov3_darknet on my own dataset I get the following result:
> > AP = 0.9828 , Precision = 0.1453 , recall = 0.9959
> > @ Iou = 0.5 :
> > mAP = 98.2826
> > mPrec = 14.5258
> > mRec = 99.588
> > Evaluation time cost = 8.11
> > --> my dataset has just one class
> > do you have an idea?why AP is high but Precision not?

Thanks a lot :)
