### ISSUE TITLE
UnboundLocalError: local variable 'yolo_model' referenced before assignment

### ISSUE THREAD

**Issue by Craftsman381** [david8862/keras-YOLOv3-model-set#59]
I try to dump model for inference but got this error.

Error:
```
/Users/bilal_temp/Environments/keras_yolo/lib/python3.7/site-packages/keras_applications/mobilenet.py:207: UserWarning: `
input_shape` is undefined or non-square, or `rows` is not in [128, 160, 192, 224]. Weights for input shape (224, 224) wil
l be loaded as the default.
  warnings.warn('`input_shape` is undefined or non-square, '
WARNING:tensorflow:From /Users/bilal_temp/Environments/keras_yolo/lib/python3.7/site-packages/tensorflow_core/python/ops/
resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) w
ith constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
OSError('Unable to open file (truncated file: eof = 1425408, sblock->base_addr = 0, stored_eof = 17225924)')
Traceback (most recent call last):
  File "yolo.py", line 85, in _generate_model
    yolo_model, _ = get_yolo3_model(self.model_type, num_feature_layers, num_anchors, num_classes, input_shape=self.model_image_size + (3,), model_pruning=self.pruning_model)
  File "/Users/bilal_temp/Downloads/keras-YOLOv3-model-set/yolo3/model.py", line 160, in get_yolo3_model
    model_body = model_function(input_tensor, num_anchors//2, num_classes)
  File "/Users/bilal_temp/Downloads/keras-YOLOv3-model-set/yolo3/models/yolo3_mobilenet.py", line 93, in tiny_yolo3_mobilenet_body
    mobilenet = MobileNet(input_tensor=inputs, weights='imagenet', include_top=False, alpha=alpha)
  File "/Users/bilal_temp/Environments/keras_yolo/lib/python3.7/site-packages/tensorflow_core/python/keras/applications/__init__.py", line 49, in wrapper
    return base_fun(*args, **kwargs)
  File "/Users/bilal_temp/Environments/keras_yolo/lib/python3.7/site-packages/tensorflow_core/python/keras/applications/mobilenet.py", line 32, in MobileNet
    return mobilenet.MobileNet(*args, **kwargs)
  File "/Users/bilal_temp/Environments/keras_yolo/lib/python3.7/site-packages/keras_applications/mobilenet.py", line 296, in MobileNet
    model.load_weights(weights_path)
  File "/Users/bilal_temp/Environments/keras_yolo/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 182, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/Users/bilal_temp/Environments/keras_yolo/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1367, in load_weights
    with h5py.File(filepath, 'r') as f:
  File "/Users/bilal_temp/Environments/keras_yolo/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/Users/bilal_temp/Environments/keras_yolo/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 1425408, sblock->base_addr = 0, stored_eof = 17225924)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yolo.py", line 419, in <module>
    yolo = YOLO_np(**vars(args))
  File "yolo.py", line 64, in __init__
    self.yolo_model = self._generate_model()
  File "yolo.py", line 95, in _generate_model
    assert yolo_model.layers[-1].output_shape[-1] == \
UnboundLocalError: local variable 'yolo_model' referenced before assignment
```
Command: 
```
python yolo.py --model_type=tiny_yolo3_mobilenet --weights_path=weights/000_ep010-loss5.500-val_loss5.516-mAP95.770.h5 --anchors_path=configs/tiny_yolo3_anchors.txt --classes_path=configs/classes.txt --model_image_size=416x416 --dump_model --output_model_file=inference_model.h5
```

I am unable to spot the problem but I think Mobilenet model is not loading, any kind of would be appreciated.

**Comment by david8862** [comment]
seems your mobilenet backbone pretrained weight file is corrupted. By default it's under $HOME/.keras/models/ for Linux platform. You can have a check.

**Comment by Craftsman381** [comment]
I am using MacOS

**Comment by david8862** [comment]
> I am using MacOS

Didn't try but I think MacOS should follow the same keras path definition :)

**Comment by shinyaogata** [comment]
I solved same error with 

`pip install h5py==2.10.0`
