### ISSUE TITLE
yolov4_mobilenet训练时打印出来的AP都是0，recall只有0.0001的水平

### ISSUE THREAD

**Issue by AnnieLavigne** [david8862/keras-YOLOv3-model-set#63]
你好，想请问下，我用你的代码训练yolov4_mobilenet，会出现下面这个报错：

Traceback (most recent call last):
  File "train.py", line 282, in <module>
    main(args)
  File "train.py", line 167, in main
    callbacks=callbacks)
  File "/home/cv2019/anaconda3/envs/keras-yolov4/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 1296, in fit_generator
    steps_name='steps_per_epoch')
  File "/home/cv2019/anaconda3/envs/keras-yolov4/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_generator.py", line 332, in model_iteration
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/cv2019/anaconda3/envs/keras-yolov4/lib/python3.6/site-packages/tensorflow_core/python/keras/callbacks.py", line 299, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/cv2019/liyueping/code/keras-YOLOv3-model-set/common/callbacks.py", line 107, in on_epoch_end
    eval_model = self.update_eval_model(self.model)
  File "/home/cv2019/liyueping/code/keras-YOLOv3-model-set/common/callbacks.py", line 64, in update_eval_model
    self.eval_model.load_weights(tmp_weights_path)
  File "/home/cv2019/anaconda3/envs/keras-yolov4/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 182, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/home/cv2019/anaconda3/envs/keras-yolov4/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 1373, in load_weights
    saving.load_weights_from_hdf5_group(f, self.layers)
  File "/home/cv2019/anaconda3/envs/keras-yolov4/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 671, in load_weights_from_hdf5_group
    ' layers.')
**ValueError: You are trying to load a weight file containing 1 layers into a model with 127 layers.**

我的解决方法是，将common/callback.py的62行
从self.eval_model.load_weights(tmp_weights_path)
改为self.eval_model.load_weights(tmp_weights_path, by_name=True)
就不会再报以上错误了。

重点在这里！！！但新的问题出现了，我训练时打印出来的AP都是0，recall只有0.0001的水平。已经40个epoch了还是如此。请问一下可能什么原因？

数据集是coco数据集的简化版，6类，4个gpu训练，v100，416x416

**Comment by david8862** [comment]
这是因为在实现online_eval时使用了一个技巧，将train model先保存为临时文件，然后再构造eval model并load训练的权重进行eval。你遇到的错误应该是临时模型文件没有正常生成，导致用于eval的模型没有正确包含训练出的权重，所以得不到eval结果。
可以看看是不是没有临时目录的读写权限。如果无法解决的话可以关闭online_eval功能，手动导出model进行eval
