### ISSUE TITLE
Error will be reported when using multi GPU training

### ISSUE THREAD

**Issue by johnjunjun7** [david8862/keras-YOLOv3-model-set#7]
Error will be reported when using multi GPU training：
`2019-11-01 01:48:36.216608: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3000000000 Hz
2019-11-01 01:48:36.224246: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5e653e0 executing computations on platform Host. Devices:
2019-11-01 01:48:36.224265: I tensorflow/compiler/xla/service/service.cc:175] StreamExecutor device (0): ,
2019-11-01 01:48:36.227256: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: Tesla V100-SXM2-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:5f:00.0
2019-11-01 01:48:36.229479: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties:
name: Tesla V100-SXM2-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:b5:00.0
2019-11-01 01:48:36.231677: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 2 with properties:
name: Tesla V100-SXM2-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:e1:00.0
2019-11-01 01:48:36.233870: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 3 with properties:
name: Tesla V100-SXM2-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:e9:00.0
2019-11-01 01:48:36.234257: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-11-01 01:48:36.236073: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-11-01 01:48:36.474272: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-11-01 01:48:37.316157: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-11-01 01:48:37.318457: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-11-01 01:48:37.508345: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-11-01 01:48:37.513144: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-11-01 01:48:37.531128: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1, 2, 3
2019-11-01 01:48:37.531213: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-11-01 01:48:37.541570: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-01 01:48:37.541599: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165] 0 1 2 3
2019-11-01 01:48:37.541608: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0: N Y Y Y
2019-11-01 01:48:37.541614: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 1: Y N Y Y
2019-11-01 01:48:37.541619: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 2: Y Y N Y
2019-11-01 01:48:37.541625: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 3: Y Y Y N
2019-11-01 01:48:37.556210: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 29232 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-32GB, pci bus id: 0000:5f:00.0, compute capability: 7.0)
2019-11-01 01:48:37.561462: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 29232 MB memory) -> physical GPU (device: 1, name: Tesla V100-SXM2-32GB, pci bus id: 0000:b5:00.0, compute capability: 7.0)
2019-11-01 01:48:37.564920: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 29232 MB memory) -> physical GPU (device: 2, name: Tesla V100-SXM2-32GB, pci bus id: 0000:e1:00.0, compute capability: 7.0)
2019-11-01 01:48:37.568040: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 29232 MB memory) -> physical GPU (device: 3, name: Tesla V100-SXM2-32GB, pci bus id: 0000:e9:00.0, compute capability: 7.0)
W1101 01:48:37.577181 140049150064384 module_wrapper.py:136] From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/module_wrapper.py:163: The name tf.keras.backend.set_session is deprecated. Please use tf.compat.v1.keras.backend.set_session instead.
W1101 01:48:37.584117 140049150064384 callbacks.py:861] `period` argument is deprecated. Please use `save_freq` to specify the frequency in number of samples seen.
/code/b3b0ddd0fba111e98f3c179718b434c4/yolo3/model.py:87: UserWarning: YOLO nano model doesn't support dynamic input shape, so just use fixed (416, 416,3) input tensor
warnings.warn("YOLO nano model doesn't support dynamic input shape, so just use fixed (416, 416,3) input tensor")
W1101 01:48:37.712170 140049150064384 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/resource_variable_ops.py:1633: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
W1101 01:48:45.379759 140049150064384 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/backend.py:3999: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W1101 01:49:06.277320 140049150064384 network.py:1484] Model inputs must come from `tf.keras.Input` (thus holding past layer metadata), they cannot be the output of a previous non-Input layer. Here, a tensor specified as input to "model_3" was not an Input tensor, it was generated by layer y_true_0.
Note that input tensors are instantiated via `tensor = tf.keras.Input(shape)`.
The tensor that caused the issue was: y_true_0:0
W1101 01:49:06.277509 140049150064384 network.py:1484] Model inputs must come from `tf.keras.Input` (thus holding past layer metadata), they cannot be the output of a previous non-Input layer. Here, a tensor specified as input to "model_3" was not an Input tensor, it was generated by layer y_true_1.
Note that input tensors are instantiated via `tensor = tf.keras.Input(shape)`.
The tensor that caused the issue was: y_true_1:0
W1101 01:49:06.277553 140049150064384 network.py:1484] Model inputs must come from `tf.keras.Input` (thus holding past layer metadata), they cannot be the output of a previous non-Input layer. Here, a tensor specified as input to "model_3" was not an Input tensor, it was generated by layer y_true_2.
Note that input tensors are instantiated via `tensor = tf.keras.Input(shape)`.
The tensor that caused the issue was: y_true_2:0
Create YOLOv3 nano model with 9 anchors and 80 classes.
model layer size: 353
Freeze the first 0 layers of total 353 layers.
Model: "model_3"
__________________________________________________________________________________________________
Layer (type) Output Shape Param # Connected to
==================================================================================================
image_input (InputLayer) [(None, 416, 416, 3) 0
__________________________________________________________________________________________________
y_true_0 (InputLayer) [(None, None, None, 0
__________________________________________________________________________________________________
y_true_1 (InputLayer) [(None, None, None, 0
__________________________________________________________________________________________________
y_true_2 (InputLayer) [(None, None, None, 0
__________________________________________________________________________________________________
lambda (Lambda) (None, 416, 416, 3) 0 image_input[0][0]
__________________________________________________________________________________________________
lambda_1 (Lambda) (None, None, None, 3 0 y_true_0[0][0]
__________________________________________________________________________________________________
lambda_2 (Lambda) (None, None, None, 3 0 y_true_1[0][0]
__________________________________________________________________________________________________
lambda_3 (Lambda) (None, None, None, 3 0 y_true_2[0][0]
__________________________________________________________________________________________________
lambda_4 (Lambda) (None, 416, 416, 3) 0 image_input[0][0]
__________________________________________________________________________________________________
lambda_5 (Lambda) (None, None, None, 3 0 y_true_0[0][0]
__________________________________________________________________________________________________
lambda_6 (Lambda) (None, None, None, 3 0 y_true_1[0][0]
__________________________________________________________________________________________________
lambda_7 (Lambda) (None, None, None, 3 0 y_true_2[0][0]
__________________________________________________________________________________________________
lambda_8 (Lambda) (None, 416, 416, 3) 0 image_input[0][0]
__________________________________________________________________________________________________
lambda_9 (Lambda) (None, None, None, 3 0 y_true_0[0][0]
__________________________________________________________________________________________________
lambda_10 (Lambda) (None, None, None, 3 0 y_true_1[0][0]
__________________________________________________________________________________________________
lambda_11 (Lambda) (None, None, None, 3 0 y_true_2[0][0]
__________________________________________________________________________________________________
lambda_12 (Lambda) (None, 416, 416, 3) 0 image_input[0][0]
__________________________________________________________________________________________________
lambda_13 (Lambda) (None, None, None, 3 0 y_true_0[0][0]
__________________________________________________________________________________________________
lambda_14 (Lambda) (None, None, None, 3 0 y_true_1[0][0]
__________________________________________________________________________________________________
lambda_15 (Lambda) (None, None, None, 3 0 y_true_2[0][0]
__________________________________________________________________________________________________
model_2 (Model) (1,) 4841590 lambda[0][0]
lambda_1[0][0]
lambda_2[0][0]
lambda_3[0][0]
lambda_4[0][0]
lambda_5[0][0]
lambda_6[0][0]
lambda_7[0][0]
lambda_8[0][0]
lambda_9[0][0]
lambda_10[0][0]
lambda_11[0][0]
lambda_12[0][0]
lambda_13[0][0]
lambda_14[0][0]
lambda_15[0][0]
__________________________________________________________________________________________________
yolo_loss (Concatenate) (4,) 0 model_2[1][0]
model_2[2][0]
model_2[3][0]
model_2[4][0]
==================================================================================================
Total params: 4,841,590
Trainable params: 4,794,184
Non-trainable params: 47,406
__________________________________________________________________________________________________
Initial training stage
Train on 82081 samples, val on 40137 samples, with batch size 16, input_shape (416, 416).
Epoch 1/20
Traceback (most recent call last):
File "train.py", line 303, in
_main(args)
File "train.py", line 178, in _main
callbacks=callbacks)
File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training.py", line 1272, in fit_generator
steps_name='steps_per_epoch')
File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_generator.py", line 265, in model_iteration
batch_outs = batch_function(*batch_data)
File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training.py", line 961, in train_on_batch
self._assert_compile_was_called()
File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training.py", line 2822, in _assert_compile_was_called
raise RuntimeError('You must compile your model before '
RuntimeError: You must compile your model before training/testing. Use `model.compile(optimizer, loss)`.`
Is there anything that needs to be changed? very Thanks :P

**Comment by david8862** [comment]
have submit fix for this issue. Actually I didn't verify the multi gpu training process since I didn't have such machine :P. So many thanks for your info.

**Comment by johnjunjun7** [comment]
many thanks ！:p
