### ISSUE TITLE
Unable to use tfrecord generator inside the model.fit because tf.dataset.map won’t return the tensors in the requested format

### ISSUE THREAD

**Issue by mvanlierBCG** [david8862/keras-YOLOv3-model-set#73]
To speed-up training, I am constructing a dataset pipeline, as suggested by Google: [tf how to make data pipelines](https://www.tensorflow.org/guide/data) [tf data performance ](https://www.tensorflow.org/guide/data_performance), which can also be used with Keras.

The serialized data is saved in several tfrecord files where each file contains N images and the gt labels as (train-001.tfrecord, train-002.tfrecord…)
For training purposes, these files are fed to the `model.fit()` function through a dataset generator in the following manner:

```
def yolo3_tf(tfrecords_dir, parser, batch_size):
    files = tf.io.matching_files(os.path.join(tfrecords_dir))
    shards = tf.data.Dataset.from_tensor_slices(files)
    shards = shards.shuffle(tf.cast(tf.shape(files)[0], tf.int64))  
    shards = shards.repeat()
    # Parallelize data reading
    dataset = shards.interleave(tf.data.TFRecordDataset)
    dataset = dataset.shuffle(buffer_size=8192)
    dataset = dataset.map(map_func=lambda x:parser(x,batch_size))  
    dataset = dataset.batch(batch_size, drop_remainder=True)
    # Cache data
    dataset = dataset.cache() 
    dataset = dataset.prefetch(batch_size)
    return dataset
```

where the output of the parser is (for yolov3 tiny assuming 2 feature layers):
`return [image, *y_true]`
with y_true defined as:
` y_true = [y_true0, y_true1]`
or for yolov3 (assuming 3 feature layers):
` y_true = [y_true0, y_true1, y_true2]`

The problem herein is that the model is created in a way that it accepts data from the generator in a specific format. The model definition looks like this: 
` model = Model([model_body.input, *y_true], model_loss)`
Where model_body.input is the image and y_true are the ground truth for layers which are responsible for detecting boxes of different sizes. Tiny yolov3 has two of them and therefore,` y_true = [y_true0,y_true1]` and yolov3 has 3 which now gives` y_true = [y_true0,y_true1, y_true2]`. Therefore the data generator is supposed to give the data in the following format which is possible with a conventional data generator `yolo3_data_generator()`, `from yolo3.data.py` you made:
`yield [image_data, *y_true], np.zeros(batch_size)`
or in the case of Yolov3 tiny:
`return [image, [y_true0,y_true1]], np.zeros(batch_size)`

Here the output (for tiny yolov3) is a list of numpy arrays where `output[0] = [image, [y_true0,y_true1]]` and `output[1] = np.zeros(batch_size)`. Again output[0][0] is the image of size [batch_size]x[width]x[height]x[depth] and so on.

**However, when using the map function following situation occurs:**
1. Use the current implementation where the map function returns [image, *y_true]. In this case we get the error
`AssertionError: Could not compute output Tensor("yolo_loss/Identity:0", shape=(1,), dtype=float32)`
This is because the generator outputs a touple of three tensors where the tensors are respectively; `image`, `y_true0 `and `y_true1 `of shapes: (32, 416, 416, 3), (32, 13, 13, 3, 6), (32, 26, 26, 3, 6), where 32 is the batch size while the expected output is a touple of obj1 and obj2 where obj1 is a list:` [image, [y_true0,y_true1]]` and obj2 is `np.zeros(batch_size)`.

**Another issue where we modify the `tf.data.Dataset.map()` function to also output a tensor of zeros by returning: `return [image, *y_true], tf.zeros(batch_size),` **

1. We get the following error:
 `Unsupported return value from function passed to Dataset.map(): ([<tf.Tensor 'Reshape:0' shape=(None, None, None) dtype=float64>, <tf.Tensor 'Reshape_1:0' shape=(None, None, None, None) dtype=float32>, <tf.Tensor 'Reshape_2:0' shape=(None, None, None, None) dtype=float32>], <tf.Tensor 'zeros:0' shape=(32,) dtype=float32>).`

Therefore, to use the tfrecords, we are currently creating an iterator of the dataset and feeding the data back in a while loop, which seems to be working but therefore I am unable to use the features such as ` tf.data.Dataset.prefetch()`, ` tf.data.Dataset.reshuffle ()`, ` tf.data.Dataset.repeat()` and num_parallel_calls, which can massively speed-up de data pipeline. 

Would you know what can we do to either modify our network or how to return a list of tensors of different sizes to the map function so that we can use tfrecords efficiently and in the way it is advised to use by Google itself? If something is unclear, please let me know that I can clarify that.

**Comment by david8862** [comment]
Hi @mvanlierBCG , I haven't try to use tf.data for data feeding to accelerate the training process in this repo, but generally it's right that the map function may not fit for the normal model.fit() API here since we use the Lambda layer trick for calucalting loss. The standard TF style solution is switching model.fit() to a custom training loop, so that you can easily fetching the images and labels from tf.data for forward/backward propagation.
Another speeding-up workaround is using Keras Sequence mechanism instead of normal python generator, and "use_multiprocessing" & "workers" option in model.fit() for parallize data feeding. I add an implementation [here](https://github.com/david8862/keras-YOLOv3-model-set/blob/master/train.py#L92) but not enabled by default since it has conflict with multiscale training.

**Comment by bsugerman** [comment]
I too am interested in accelerating training times using tf.data, however it seems that you are trying to use every trick possible at once in your function. Has anyone tried just using prefetching, for example? Certainly if there is a way to use the existing generators with tf.data, then even just a prefetch or an interleave is a big improvement.

**Comment by ksv87** [comment]
@david8862 i trying use Yolo5DataGenerator (without multiscale) 
and 
```
    model.fit_generator(train_data_generator,
    # model.fit_generator(data_generator(dataset[:num_train], args.batch_size, input_shape, anchors, num_classes, args.enhance_augment, rescale_interval, multi_anchor_assign=args.multi_anchor_assign),
        # steps_per_epoch=max(1, num_train//args.batch_size),
        validation_data=val_data_generator,
        # validation_data=data_generator(dataset[num_train:], args.batch_size, input_shape, anchors, num_classes, multi_anchor_assign=args.multi_anchor_assign),
        # validation_steps=max(1, num_val//args.batch_size),
        epochs=args.total_epoch,
        initial_epoch=epochs,
        #verbose=1,
        workers=4,
        use_multiprocessing=True,
        max_queue_size=40,
        callbacks=callbacks)
```

and i getting error
```
355/503 [====================>.........] - ETA: 1:02 - loss: 2833.4062 - location_loss: 17.6781 - confidence_loss: 2773.6956 - class_loss: 42.0000Traceback (most recent call last):
  File "D:\research\keras-YOLOv3-model-set\train.py", line 325, in <module>
    main(args)
  File "D:\research\keras-YOLOv3-model-set\train.py", line 232, in main
    model.fit_generator(train_data_generator,
  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\keras\engine\training.py", line 2209, in fit_generator
    return self.fit(
  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\tensorflow\python\eager\execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: Graph execution error:

2 root error(s) found.
  (0) UNKNOWN:  IndexError: list index out of range
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\ksv\.conda\envs\keras\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\keras\utils\data_utils.py", line 566, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "D:\research\keras-YOLOv3-model-set\yolo5\data.py", line 153, in __getitem__
    image, box = get_ground_truth_data(batch_annotation_lines[b], self.input_shape, augment=True)
IndexError: list index out of range
"""


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\tensorflow\python\ops\script_ops.py", line 271, in __call__
    ret = func(*args)

  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1004, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\keras\engine\data_adapter.py", line 830, in wrapped_generator
    for data in generator_fn():

  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\keras\utils\data_utils.py", line 785, in get
    raise e

  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\keras\utils\data_utils.py", line 776, in get
    inputs = self.queue.get(block=True, timeout=5).get()

  File "C:\Users\ksv\.conda\envs\keras\lib\multiprocessing\pool.py", line 774, in get
    raise self._value

IndexError: list index out of range


         [[{{node PyFunc}}]]
         [[IteratorGetNext]]
         [[IteratorGetNext/_8]]
  (1) UNKNOWN:  IndexError: list index out of range
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\ksv\.conda\envs\keras\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\keras\utils\data_utils.py", line 566, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "D:\research\keras-YOLOv3-model-set\yolo5\data.py", line 153, in __getitem__
    image, box = get_ground_truth_data(batch_annotation_lines[b], self.input_shape, augment=True)
IndexError: list index out of range
"""


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\tensorflow\python\ops\script_ops.py", line 271, in __call__
    ret = func(*args)

  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1004, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\keras\engine\data_adapter.py", line 830, in wrapped_generator
    for data in generator_fn():

  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\keras\utils\data_utils.py", line 785, in get
    raise e

  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\keras\utils\data_utils.py", line 776, in get
    inputs = self.queue.get(block=True, timeout=5).get()

  File "C:\Users\ksv\.conda\envs\keras\lib\multiprocessing\pool.py", line 774, in get
    raise self._value

IndexError: list index out of range


         [[{{node PyFunc}}]]
         [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_43448]
```

**Comment by ksv87** [comment]
if use_multiprocessing=False and worker=1 i getting error
```
 2/503 [..............................] - ETA: 1:00 - loss: 7095.3076 - location_loss: 24.2790 - confidence_loss: 6999.6465 - class_loss: 71.3489   Traceback (most recent call last):
  File "D:\research\keras-YOLOv3-model-set\train.py", line 325, in <module>
    main(args)
  File "D:\research\keras-YOLOv3-model-set\train.py", line 232, in main
    model.fit_generator(train_data_generator,
  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\keras\engine\training.py", line 2209, in fit_generator
    return self.fit(
  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\tensorflow\python\eager\execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: Graph execution error:

2 root error(s) found.
  (0) UNKNOWN:  IndexError: list index out of range
Traceback (most recent call last):

  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\tensorflow\python\ops\script_ops.py", line 271, in __call__
    ret = func(*args)

  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1004, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\keras\engine\data_adapter.py", line 830, in wrapped_generator
    for data in generator_fn():

  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\keras\engine\data_adapter.py", line 956, in generator_fn
    yield x[i]

  File "D:\research\keras-YOLOv3-model-set\yolo5\data.py", line 153, in __getitem__
    image, box = get_ground_truth_data(batch_annotation_lines[b], self.input_shape, augment=True)

IndexError: list index out of range


         [[{{node PyFunc}}]]
         [[IteratorGetNext]]
         [[IteratorGetNext/_6]]
  (1) UNKNOWN:  IndexError: list index out of range
Traceback (most recent call last):

  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\tensorflow\python\ops\script_ops.py", line 271, in __call__
    ret = func(*args)

  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1004, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\keras\engine\data_adapter.py", line 830, in wrapped_generator
    for data in generator_fn():

  File "C:\Users\ksv\.conda\envs\keras\lib\site-packages\keras\engine\data_adapter.py", line 956, in generator_fn
    yield x[i]

  File "D:\research\keras-YOLOv3-model-set\yolo5\data.py", line 153, in __getitem__
    image, box = get_ground_truth_data(batch_annotation_lines[b], self.input_shape, augment=True)

IndexError: list index out of range


         [[{{node PyFunc}}]]
         [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_43450]
```

error in this section on line 153, but i dont understand what is wrong

https://github.com/david8862/keras-YOLOv3-model-set/blob/0c14421535623ec8c18fd2e8854574b85b28bf10/yolo5/data.py#L138-L157

**Comment by ksv87** [comment]
i found a reason

https://github.com/david8862/keras-YOLOv3-model-set/blob/0c14421535623ec8c18fd2e8854574b85b28bf10/yolo5/data.py#L134-L136

i changed it to, and it fix error

    def __len__(self):
        # get iteration loops on each epoch
        return max(1, math.floor(len(self.annotation_lines) / float(self.batch_size)))
